# Generated by Django 3.2.9 on 2022-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0002_auto_20220314_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_test',
            name='test_level',
            field=models.CharField(choices=[('1', 'level-1'), ('2', 'level-2'), ('3', 'level-3')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='create_test',
            name='test_set',
            field=models.CharField(choices=[('1', 'set-1'), ('2', 'set-2'), ('3', 'set-3'), ('4', 'set-4'), ('5', 'set-5'), ('6', 'set-6'), ('7', 'set-7'), ('8', 'set-8'), ('9', 'set-9'), ('10', 'set-10')], default='1', max_length=10),
        ),
    ]
