# Generated by Django 3.2.7 on 2022-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220218_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='first_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
