# Generated by Django 3.2.9 on 2022-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_profile_first_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='first_attempt',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='firstMonday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
