# Generated by Django 3.2.9 on 2022-03-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220226_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal_users',
            name='referal_id',
        ),
        migrations.RemoveField(
            model_name='referal_users',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='referal_id',
        ),
        migrations.DeleteModel(
            name='referal',
        ),
        migrations.DeleteModel(
            name='referal_users',
        ),
    ]
