# Generated by Django 3.2.9 on 2022-04-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_alter_referal_code_qr_code_number'),
        ('test_series', '0004_alter_create_test_test_level'),
        ('students', '0005_auto_20220331_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='lurnifighter_badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_name', models.CharField(max_length=50)),
                ('weekly_challenges', models.IntegerField(blank=True, null=True)),
                ('ask_for_fee', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lurnifighter Badges',
                'verbose_name_plural': 'Lurnifighter Badges',
            },
        ),
        migrations.CreateModel(
            name='student_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='student_qr_code')),
                ('qr_wroth', models.CharField(blank=True, default='5', help_text='it will be calculated in %', max_length=10, null=True)),
                ('adding_limit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student_profile',
            name='referal_code_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.referal_code'),
        ),
        migrations.CreateModel(
            name='test_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_series.create_test')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='students_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_get_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_get_student', to='students.student_profile')),
                ('referral_sent_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_sent_student', to='students.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='lurnifighter_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_start_date', models.DateField(blank=True, null=True)),
                ('level_end_date', models.DateField(blank=True, null=True)),
                ('challenge_completed', models.IntegerField(blank=True, null=True)),
                ('level_status', models.CharField(choices=[('completed', 'completed'), ('incomplete', 'incomplete')], max_length=100)),
                ('lurnifighter_badges_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lurnifighter_badges')),
                ('student_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
            options={
                'verbose_name': 'Lurnifighter Levels',
                'verbose_name_plural': 'Lurnifighter Levels',
            },
        ),
    ]
