# Generated by Django 3.2.9 on 2022-04-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20220404_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lurnifighter_badges',
            options={'verbose_name': 'Creates Lurnifighter Levels', 'verbose_name_plural': 'Creates Lurnifighter Levels'},
        ),
        migrations.RemoveField(
            model_name='lurnifighter_badges',
            name='ask_for_fee',
        ),
        migrations.AddField(
            model_name='lurnifighter_badges',
            name='crowns',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_badges',
            name='refer_freinds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_badges',
            name='study_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_badges',
            name='tests',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_badges',
            name='win_coupons',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='lurnifighter_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_received', models.IntegerField(blank=True, null=True)),
                ('coupon_used', models.IntegerField(blank=True, null=True)),
                ('lurnifighter_badges_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lurnifighter_badges')),
                ('student_profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
        ),
    ]
