# Generated by Django 3.2.9 on 2022-04-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20220404_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lurnifighter_coupons',
            name='lurnifighter_badges_id',
        ),
        migrations.RemoveField(
            model_name='lurnifighter_coupons',
            name='student_profile_id',
        ),
        migrations.RemoveField(
            model_name='lurnifighter_levels',
            name='lurnifighter_badges_id',
        ),
        migrations.RemoveField(
            model_name='lurnifighter_levels',
            name='student_profile_id',
        ),
        migrations.DeleteModel(
            name='lurnifighter_badges',
        ),
        migrations.DeleteModel(
            name='lurnifighter_coupons',
        ),
        migrations.DeleteModel(
            name='lurnifighter_levels',
        ),
    ]
