# Generated by Django 3.2.9 on 2022-04-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0008_auto_20220406_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='lurnifighter_badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creates Lurnifighter Levels',
                'verbose_name_plural': 'Creates Lurnifighter Levels',
            },
        ),
        migrations.CreateModel(
            name='lurnifighter_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_name', models.CharField(max_length=50)),
                ('reffrral_count', models.IntegerField(blank=True, default=0, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creates Lurnifighter Badges',
                'verbose_name_plural': 'Creates Lurnifighter Badges',
            },
        ),
        migrations.CreateModel(
            name='weekly_challange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_name', models.CharField(max_length=50)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('total_study_hours', models.FloatField(blank=True, null=True)),
                ('total_test', models.IntegerField(blank=True, default=0, null=True)),
                ('total_crowns', models.IntegerField(blank=True, default=0, null=True)),
                ('refer_freinds', models.IntegerField(blank=True, default=0, null=True)),
                ('test_performances', models.FloatField(blank=True, default=0, null=True)),
                ('study_effectiveness', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lurnifighter_badges_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lurnifighter_badges')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='weekly_reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trophy', models.BooleanField(default=True)),
                ('no_of_coins', models.BigIntegerField(blank=True, default=0, null=True)),
                ('refer_freind_coupons', models.IntegerField(blank=True, default=0, null=True)),
                ('cash_coupons', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weekly_challange_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.weekly_challange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='referral_and_winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lurnifighter_referral_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lurnifighter_referral')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='lurnifighter_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_start_date', models.DateField(blank=True, null=True)),
                ('level_end_date', models.DateField(blank=True, null=True)),
                ('challenge_completed', models.IntegerField(blank=True, null=True)),
                ('level_status', models.CharField(choices=[('completed', 'completed'), ('incomplete', 'incomplete')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
                ('weekly_challange_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.weekly_challange')),
                ('weekly_reward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.weekly_reward')),
            ],
            options={
                'verbose_name': 'Lurnifighter Levels',
                'verbose_name_plural': 'Lurnifighter Levels',
            },
        ),
        migrations.CreateModel(
            name='lurnifighter_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_received', models.IntegerField(blank=True, null=True)),
                ('coupon_used', models.IntegerField(blank=True, null=True)),
                ('lurnifighter_badges_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lurnifighter_badges')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='lurnifighter_badges_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lurnifighter_badges_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.lurnifighter_badges')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
        ),
    ]
