# Generated by Django 3.2.9 on 2022-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_lurnifighter_badges_lurnifighter_badges_status_lurnifighter_coupons_lurnifighter_levels_lurnifighter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lurnifighter_referral',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lurnifighter_referral',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
