# Generated by Django 3.2.9 on 2022-04-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_auto_20220407_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_no', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Academic Update Limit',
                'verbose_name_plural': 'Academic Update Limits',
            },
        ),
        migrations.CreateModel(
            name='cash_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_name', models.CharField(max_length=50)),
                ('coupon_value', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lurnifighter_coupons',
            options={'verbose_name': 'Lurnifighter Acuried Referral Coupons', 'verbose_name_plural': 'Lurnifighter Acuried Referral Coupons'},
        ),
        migrations.RenameField(
            model_name='lurnifighter_coupons',
            old_name='coupon_received',
            new_name='referral_coupon',
        ),
        migrations.RemoveField(
            model_name='lurnifighter_coupons',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='lurnifighter_coupons',
            name='lurnifighter_badges_id',
        ),
        migrations.RemoveField(
            model_name='weekly_reward',
            name='cash_coupons',
        ),
        migrations.AddField(
            model_name='lurnifighter_coupons',
            name='weekly_challange_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.weekly_challange'),
        ),
        migrations.AddField(
            model_name='lurnifighter_coupons',
            name='weekly_reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.weekly_reward'),
        ),
        migrations.AddField(
            model_name='lurnifighter_levels',
            name='coupon_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_levels',
            name='coupon_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='lurnifighter_cashcoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_for', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_coupons_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.cash_coupons')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
            options={
                'verbose_name': 'Lurnifighter Acuried Cash Coupons',
                'verbose_name_plural': 'Lurnifighter Acuried Cash Coupons',
            },
        ),
        migrations.AddField(
            model_name='weekly_reward',
            name='cash_coupons_id',
            field=models.ManyToManyField(blank=True, to='students.cash_coupons'),
        ),
    ]
