# Generated by Django 3.2.9 on 2022-04-12 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0012_auto_20220411_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_challange_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_performance', models.IntegerField()),
                ('weekly_challange', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Create Monthly Challange Criteria',
                'verbose_name_plural': 'Create Monthly Challange Criteria',
            },
        ),
        migrations.CreateModel(
            name='monthly_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_performance', models.IntegerField()),
                ('weekly_challange', models.IntegerField()),
                ('month_name', models.CharField(choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=50)),
                ('certificate', models.BooleanField(default=False)),
                ('monthly_challange_criteria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.monthly_challange_criteria')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
            options={
                'verbose_name': 'Lurnifighter Monthly Certificates',
                'verbose_name_plural': 'Lurnifighter Monthly Certificates',
            },
        ),
    ]
