# Generated by Django 3.2.9 on 2022-04-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_monthly_certificate_monthly_challange_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_details',
            name='academic_limits_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academic_limits'),
        ),
        migrations.AddField(
            model_name='academic_details',
            name='academic_update_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
