# Generated by Django 3.2.9 on 2022-04-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0014_auto_20220414_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_day', models.DateField()),
                ('crown', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Create Daily Challenge',
                'verbose_name_plural': 'Create Daily Challenge',
            },
        ),
        migrations.CreateModel(
            name='test_and_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=50)),
                ('coins', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Create Daily Challenge Test and Study',
                'verbose_name_plural': 'Create Daily Challenge Test and Study',
            },
        ),
        migrations.CreateModel(
            name='lurnifighter_daily_challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins', models.IntegerField(default=0)),
                ('total_crown', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='students.daily_challenge')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
        ),
        migrations.AddField(
            model_name='daily_challenge',
            name='test_and_study_id',
            field=models.ManyToManyField(related_name='test_and_studys', to='students.test_and_study'),
        ),
        migrations.AddField(
            model_name='daily_challenge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
