# Generated by Django 3.2.9 on 2022-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20220414_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_coupons',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lurnifighter_cashcoupons',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
