# Generated by Django 3.2.9 on 2022-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_test_and_study_crowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='students_images'),
        ),
    ]
