# Generated by Django 3.2.9 on 2022-04-22 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_coupons',
            name='expires_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
