# Generated by Django 3.2.9 on 2022-04-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0001_initial'),
        ('courses', '0014_auto_20220311_0503'),
        ('students', '0019_cash_coupons_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_date', models.DateField()),
                ('total_amount', models.BigIntegerField(default=0)),
                ('remain_amount', models.BigIntegerField(default=0)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('total_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.payment_allow_days')),
                ('course_dates_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_dates')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
            ],
            options={
                'verbose_name': 'Student  Payments',
                'verbose_name_plural': 'Student  Payments',
            },
        ),
        migrations.CreateModel(
            name='payment_installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('installment_amount', models.BigIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
                ('student_payments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student_payments')),
            ],
        ),
    ]
