# Generated by Django 3.2.9 on 2022-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_payment_installments_student_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='zip_code',
            new_name='pin_code',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='coaching_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='coaching_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='course_program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
