# Generated by Django 3.2.9 on 2022-04-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_academic_limits'),
        ('students', '0021_auto_20220423_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_details',
            name='academic_limits_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_section.academic_limits'),
        ),
        migrations.DeleteModel(
            name='academic_limits',
        ),
    ]
