# Generated by Django 3.2.9 on 2022-04-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_cash_coupons'),
        ('students', '0022_auto_20220426_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lurnifighter_cashcoupons',
            name='cash_coupons_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.cash_coupons'),
        ),
        migrations.AlterField(
            model_name='weekly_reward',
            name='cash_coupons_id',
            field=models.ManyToManyField(blank=True, to='admin_section.cash_coupons'),
        ),
        migrations.DeleteModel(
            name='cash_coupons',
        ),
    ]
