# Generated by Django 3.2.9 on 2022-04-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_monthly_challange_criteria'),
        ('students', '0023_auto_20220426_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_certificate',
            name='monthly_challange_criteria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.monthly_challange_criteria'),
        ),
        migrations.DeleteModel(
            name='monthly_challange_criteria',
        ),
    ]
