# Generated by Django 3.2.9 on 2022-04-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0005_lurnifighter_badges_weekly_challange_weekly_reward'),
        ('students', '0024_auto_20220426_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_challange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='weekly_challange',
            name='lurnifighter_badges_id',
        ),
        migrations.RemoveField(
            model_name='weekly_challange',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='weekly_reward',
            name='cash_coupons_id',
        ),
        migrations.RemoveField(
            model_name='weekly_reward',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='weekly_reward',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='weekly_reward',
            name='weekly_challange_id',
        ),
        migrations.AlterField(
            model_name='lurnifighter_badges_status',
            name='lurnifighter_badges_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_section.lurnifighter_badges'),
        ),
        migrations.AlterField(
            model_name='lurnifighter_coupons',
            name='weekly_challange_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.weekly_challange'),
        ),
        migrations.AlterField(
            model_name='lurnifighter_coupons',
            name='weekly_reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.weekly_reward'),
        ),
        migrations.AlterField(
            model_name='lurnifighter_levels',
            name='weekly_challange_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.weekly_challange'),
        ),
        migrations.AlterField(
            model_name='lurnifighter_levels',
            name='weekly_reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_section.weekly_reward'),
        ),
        migrations.DeleteModel(
            name='lurnifighter_badges',
        ),
        migrations.DeleteModel(
            name='weekly_challange',
        ),
        migrations.DeleteModel(
            name='weekly_reward',
        ),
    ]
