# Generated by Django 3.2.9 on 2022-04-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0007_daily_challenge_test_and_study'),
        ('students', '0026_auto_20220426_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_and_study',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='test_and_study',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='lurnifighter_daily_challenge',
            name='daily_challenge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='admin_section.daily_challenge'),
        ),
        migrations.DeleteModel(
            name='daily_challenge',
        ),
        migrations.DeleteModel(
            name='test_and_study',
        ),
    ]
