# Generated by Django 3.2.9 on 2022-04-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0007_daily_challenge_test_and_study'),
        ('students', '0027_auto_20220426_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lurnifighter_daily_challenge',
            name='daily_challenge_id',
        ),
        migrations.AddField(
            model_name='lurnifighter_daily_challenge',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lurnifighter_daily_challenge',
            name='test_and_study_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_studies', to='admin_section.test_and_study'),
            preserve_default=False,
        ),
    ]
