# Generated by Django 3.2.9 on 2022-04-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220311_0503'),
        ('students', '0028_auto_20220426_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterDuration', models.IntegerField(blank=True, default=0, null=True)),
                ('newChapterDuration', models.IntegerField(blank=True, default=0, null=True)),
                ('topicDuration', models.IntegerField(blank=True, default=0, null=True)),
                ('newTopicDuration', models.IntegerField(blank=True, default=0, null=True)),
                ('startDatetime', models.DateTimeField(blank=True, null=True)),
                ('endDatetime', models.DateTimeField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('studiedTime', models.TimeField(blank=True, null=True)),
                ('studyStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('coins', models.BigIntegerField(blank=True, default=0, null=True)),
                ('eNess', models.CharField(blank=True, max_length=50, null=True)),
                ('totalDuration', models.BigIntegerField(blank=True, default=0, null=True)),
                ('isSync', models.IntegerField(default=0)),
                ('chapterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_profile')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjects')),
                ('topicId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
                ('unitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unit')),
            ],
            options={
                'verbose_name': 'Student  Study',
                'verbose_name_plural': 'Student  Study',
            },
        ),
    ]
