# Generated by Django 3.2.6 on 2021-08-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Register',
        ),
    ]
