# Generated by Django 3.2.6 on 2021-08-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20210812_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=255)),
                ('regularPrice', models.IntegerField(max_length=255)),
            ],
        ),
    ]
