# Generated by Django 3.2.6 on 2021-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regularPrice',
            field=models.IntegerField(),
        ),
    ]
