# Generated by Django 3.2.6 on 2021-08-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_alter_product_regularprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Question',
        ),
    ]
