# Generated by Django 3.2.6 on 2021-08-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_rename_product_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='que',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='price',
        ),
        migrations.RemoveField(
            model_name='question',
            name='regularPrice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sku',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
