# Generated by Django 3.2.6 on 2021-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_auto_20210813_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.IntegerField(auto_created=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
