# Generated by Django 3.2.6 on 2021-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.IntegerField(auto_created=True, editable=False, unique=True),
        ),
    ]
