# Generated by Django 3.2.6 on 2021-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_alter_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
