# Generated by Django 3.1.2 on 2021-08-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
