# Generated by Django 3.2.7 on 2022-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('1_year', '1 Year Programe'), ('2_year', '1 Year Programe')], max_length=100, null=True),
        ),
    ]
