# Generated by Django 3.2.9 on 2022-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dates',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
