# Generated by Django 3.2.9 on 2022-02-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220227_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
