# Generated by Django 3.2.9 on 2022-02-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220228_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Calenderimages/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Streamimages/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subjects_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectChapter', to='courses.subjects'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitChapter', to='courses.unit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='link_subjects', to='courses.subjects'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapterTopic', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectUnit', to='courses.subjects'),
        ),
        migrations.CreateModel(
            name='subbtopic_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_text', models.TextField(blank=True, null=True)),
                ('subtopic_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subtopic')),
            ],
        ),
    ]
