# Generated by Django 3.2.9 on 2022-02-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220228_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbtopic_text',
            name='subtopic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopicText', to='courses.subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicSubtopic', to='courses.topic'),
        ),
    ]
