# Generated by Django 3.2.9 on 2022-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_src', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
