# Generated by Django 3.2.9 on 2022-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_src', '0005_auto_20220418_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='s_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
