# Generated by Django 3.2.9 on 2022-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_src', '0007_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy_policy',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
