# Generated by Django 3.2.9 on 2022-04-26 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_section', '0002_academic_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('coupon_name', models.CharField(max_length=50)),
                ('coupon_value', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Coupon',
                'verbose_name_plural': 'Cash Coupons',
            },
        ),
    ]
