# Generated by Django 3.2.9 on 2022-04-26 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_section', '0005_lurnifighter_badges_weekly_challange_weekly_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='lurnifighter_referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_name', models.CharField(max_length=50)),
                ('reffrral_count', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('top', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lurnifighter Referral Badges',
                'verbose_name_plural': 'Lurnifighter Referral Badges',
            },
        ),
    ]
