# Generated by Django 3.2.9 on 2022-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referal_code',
            old_name='referal_code',
            new_name='qr_code_number',
        ),
        migrations.AddField(
            model_name='referal_code',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
